name: Issues Event Listener

on:
  issues:
    types:
      - opened
      - edited
      - closed

jobs:
  issue_event:
    runs-on: ubuntu-latest

    steps:
      - name: output issue event
        run: echo "${{ toJson(github.event) }}"
